# Generated by Django 5.1.1 on 2024-11-10 20:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=128)),
                ("user_agent", models.CharField(max_length=256)),
                ("ip_address", models.CharField(max_length=64)),
                ("ua_browser_family", models.CharField(max_length=64)),
                ("ua_browser_version", models.CharField(max_length=16)),
                ("ua_device_family", models.CharField(max_length=64)),
                ("ua_device_model", models.CharField(max_length=32)),
            ],
        ),
    ]
